apiVersion: v1
kind: Service
metadata:
  name: data-pipeline-svc
  labels:
    app: data-pipeline
    tier: backend
  annotations:
     cloud.google.com/load-balancer-type: External
spec:
  type: LoadBalancer
  selector:
    app: data-pipeline
    tier: backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
